# Generated by Django 4.2.21 on 2025-06-17 02:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planner", "0004_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("departure_iata", models.CharField(max_length=3)),
                ("arrival_iata", models.CharField(max_length=3)),
                ("offers_data", models.JSONField(blank=True, null=True)),
                (
                    "selected_offer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("selected_offer_snapshot", models.JSONField(blank=True, null=True)),
                ("last_ticketing_date", models.DateField(blank=True, null=True)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                ("price_data", models.JSONField(blank=True, null=True)),
                ("booking_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_selection",
                        to="planner.travelplan",
                    ),
                ),
            ],
        ),
    ]
