openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/onboard/countries/:
    get:
      operationId: api_onboard_countries_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
          description: ''
  /api/onboard/exchange-rate/:
    get:
      operationId: api_onboard_exchange_rate_retrieve
      description: 기준 통화와 대상 통화 간의 실시간 환율 정보 조회
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
                description: Unspecified response body
          description: ''
  /api/onboard/interests/:
    get:
      operationId: api_onboard_interests_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InterestItem'
          description: ''
  /api/onboard/load/:
    get:
      operationId: api_onboard_load_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoadOnboarding'
          description: ''
  /api/onboard/options/:
    get:
      operationId: api_onboard_options_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OnboardingOptions'
          description: ''
  /api/onboard/required-vaccines/:
    get:
      operationId: api_onboard_required_vaccines_retrieve
      parameters:
      - in: query
        name: country_code
        schema:
          type: string
        description: '국가 코드 (예: US, JP, KR)'
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: 요청한 국가에 필요한 백신 리스트
        '404':
          description: 국가 정보가 없을 때
  /api/onboard/save/:
    post:
      operationId: api_onboard_save_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveOnboarding'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SaveOnboarding'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SaveOnboarding'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
                description: Unspecified response body
          description: ''
  /api/onboard/vaccine-info/:
    get:
      operationId: api_onboard_vaccine_info_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VaccineInfo'
          description: ''
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    InterestCategoryWithItems:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/InterestItemBrief'
      required:
      - id
      - items
      - name
    InterestItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    InterestItemBrief:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
      required:
      - id
      - name
    LoadOnboarding:
      type: object
      properties:
        countries:
          type: array
          items:
            type: integer
        items:
          type: array
          items:
            type: integer
      required:
      - countries
      - items
    OnboardingOptions:
      type: object
      properties:
        countries:
          type: array
          items:
            type: object
            additionalProperties: {}
        categories:
          type: array
          items:
            $ref: '#/components/schemas/InterestCategoryWithItems'
      required:
      - categories
      - countries
    SaveOnboarding:
      type: object
      properties:
        country:
          type: integer
        items:
          type: array
          items:
            type: integer
      required:
      - country
    VaccineInfo:
      type: object
      properties:
        country:
          type: string
        required_vaccines:
          type: array
          items:
            type: string
      required:
      - country
      - required_vaccines
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
