name: "🔨 WBS 백엔드 기능 이슈"
description: "WBS 항목에 따라 백엔드 기능 이슈를 생성합니다"
title: "BE-feature_code-feature_name"
labels: []
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              **🦁 이슈 작성 전 확인 사항 (백엔드)**
              1. WBS 분류와 기능 코드를 정확히 기입했는지 확인하세요.  
              2. 인수 조건은 구현 완료 판별 기준입니다.  
              3. 필요한 하위 이슈가 있다면 마지막 필드에 링크해 주세요.

    - type: dropdown
      id: wbs_category
      attributes:
          label: "📂 WBS 기반 작업 분류"
          description: "관련된 WBS 분류를 선택하세요"
          options:
              - "1. 여행 피드"
              - "2. 여행지 정보 제공"
              - "3. 여행 계획"
              - "4. 여행자 온보딩"
              - "5. 사용자 관리"
      validations:
          required: true

    - type: input
      id: feature_code
      attributes:
          label: "🆔 기능 코드"
          description: "WBS에 정의된 코드 입력 (예: PLAN_DURATION_BUDGET)"
          placeholder: "PLAN_DURATION_BUDGET"
      validations:
          required: true

    - type: input
      id: feature_name
      attributes:
          label: "📝 기능명"
          description: "간단한 기능명 입력"
          placeholder: "TravelPlan 모델 정의"
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: "💡 작업 내용 상세"
          description: "WBS 항목에 맞춰 작업할 백엔드 내용을 상세히 작성하세요"
          placeholder: |
              TravelPlan 모델 정의:
              - start_date < end_date 유효성 검증
              - budget_limit MinValueValidator 적용
      validations:
          required: true

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: "✅ 인수 조건 (Acceptance Criteria)"
          description: |
              - 기능 명세서 및 입력, 예외 처리 등을 참고하여 만족해야 할 조건을 작성하세요.  
              - 완료 기준을 하나씩 체크박스로 작성하세요.
          placeholder: |
              - [ ] TravelPlan 모델에 validation 메소드 추가
              - [ ] admin.py에 list_display 설정 완료
      validations:
          required: true

    - type: textarea
      id: screen_elements
      attributes:
          label: "🔗 서브 이슈 (Sub-issues)"
          description: |
              - 하위 백엔드 작업 이슈를 체크리스트 형식으로 링크하세요.  
              - WBS 항목별로 추가해주세요.
          placeholder: |
              - [ ] #123 모델 정의
              - [ ] #124 serializer 작성
