name: "✨ WBS 기반 기능 이슈"
about: "WBS 항목에 따라 백엔드/프론트엔드 기능 이슈를 생성합니다"
title: "[{{component}}-{{feature_code}}] {{feature_name}}"
labels: []
assignees: []

body:
    - type: dropdown
      id: component
      attributes:
          label: "💻 컴포넌트"
          description: "백엔드와 프론트엔드 중 하나를 선택하세요"
          options:
              - "백엔드"
              - "프론트엔드"
          required: true

    - type: dropdown
      id: wbs_category
      attributes:
          label: "📂 WBS 대분류"
          description: "관련된 WBS 대분류를 선택하세요"
          options:
              - "1. 여행 기간과 예산 설정"
              - "2. 여행지 선택"
              - "3. 출발지 설정"
              - "4. 항공권 탐색 및 추천"
              - "5. 숙소 필요 여부 판단 및 탐색"
              - "6. 교통 경로 탐색 및 최적화"
              - "7. 예산 계산 및 항목 조정"
              - "8. 마이페이지 여행 계획 조회"
          required: true

    - type: input
      id: feature_code
      attributes:
          label: "🆔 기능 코드"
          description: "WBS에서 정의된 코드 입력 (예: PLAN_DURATION_BUDGET)"
          placeholder: "PLAN_DURATION_BUDGET"
          required: true

    - type: input
      id: feature_name
      attributes:
          label: "📝 기능명"
          description: "간단한 기능명 입력"
          placeholder: "TravelPlan 모델 정의"
          required: true

    - type: textarea
      id: description
      attributes:
          label: "💡 작업 내용 상세"
          description: "WBS 항목에 맞춰 작업할 내용을 상세히 작성하세요"
          placeholder: |
              TravelPlan 모델 정의:
              - start_date < end_date 유효성 검증
              - budget_limit MinValueValidator 적용
          required: true

    - type: textarea
      id: acceptance_criteria
      attributes:
          label: "✅ 인수 조건 (Acceptance Criteria)"
          description: "- 완료 기준을 하나씩 체크박스로 작성하세요"
          placeholder: |
              - [ ] TravelPlan 모델에 validation 메소드 추가
              - [ ] admin.py에 list_display 설정 완료
          required: true

    - type: textarea
      id: sub_issues
      attributes:
          label: "🔗 서브 이슈 (Sub-issues)"
          description: "하위 작업 이슈를 체크리스트 형식으로 링크하세요"
          placeholder: |
              - [ ] #123 PlaceAutocompleteAPIView 작성
              - [ ] #124 PlaceDetailAPIView 작성
          required: false
