# Generated by Django 4.2.21 on 2025-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
