# Generated by Django 4.2.21 on 2025-06-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="travel_style",
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_styles",
            field=models.ManyToManyField(
                blank=True, related_name="profiles", to="accounts.travelstyle"
            ),
        ),
    ]
