# Generated by Django 4.2.21 on 2025-06-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_travelstyle_remove_profile_travel_style_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="travel_styles",
        ),
        migrations.AddField(
            model_name="profile",
            name="travel_styles",
            field=models.CharField(
                blank=True,
                help_text="여행 스타일을 쉼표로 구분하여 입력하세요",
                max_length=500,
            ),
        ),
    ]
