# Generated by Django 4.2.21 on 2025-06-10 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_travel_styles_profile_travel_styles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="preferred_destinations",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="social_media",
        ),
    ]
