# Generated by Django 4.2.21 on 2025-06-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_preferred_destinations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="travel_experience",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="travel_styles",
        ),
    ]
