# Generated by Django 4.2.21 on 2025-06-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_travel_experience_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TravelStyle",
        ),
    ]
