# Generated by Django 4.2.21 on 2025-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
