# Generated by Django 4.2.21 on 2025-06-16 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_profile_nickname_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="verification_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
