# Generated by Django 4.2.21 on 2025-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feed",
            old_name="latitude",
            new_name="lat",
        ),
        migrations.RenameField(
            model_name="feed",
            old_name="longitude",
            new_name="lon",
        ),
        migrations.AddField(
            model_name="feed",
            name="exif_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="exif_lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
