# Generated by Django 4.2.21 on 2025-06-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_rename_latitude_feed_lat_rename_longitude_feed_lon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feed",
            name="exif_lat",
        ),
        migrations.RemoveField(
            model_name="feed",
            name="exif_lon",
        ),
    ]
