# Generated by Django 4.2.21 on 2025-06-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedimage",
            name="image",
            field=models.ImageField(upload_to="media/feeds/"),
        ),
    ]
