# Generated by Django 5.2.1 on 2025-06-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='KR', max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequiredVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.country')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.vaccine')),
            ],
            options={
                'unique_together': {('country', 'vaccine')},
            },
        ),
    ]
