# Generated by Django 5.2.1 on 2025-06-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0002_vaccine_country_code_requiredvaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=20, unique=True)),
                ('feature', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('input_condition', models.CharField(max_length=100)),
                ('output_description', models.TextField()),
                ('fallback_message', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='onboard.checklistcategory')),
            ],
        ),
    ]
