# Generated by Django 5.2.1 on 2025-06-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0003_checklistcategory_checklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
