# Generated by Django 4.2.20 on 2025-06-22 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onboard', '0004_country_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=50)),
                ('is_checked', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboard.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'country', 'req_id')},
            },
        ),
    ]
