# Generated by Django 4.2.20 on 2025-06-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0005_checklistitem_detail_userchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='name',
            field=models.CharField(default='이름없음', max_length=255),
        ),
    ]
