# Generated by Django 4.2.21 on 2025-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_alter_travelplan_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelplan",
            name="status",
            field=models.CharField(
                choices=[("draft", "임시저장"), ("confirmed", "확정")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="travelplan",
            name="updated_at",
            field=models.DateTimeField(blank=True),
        ),
    ]
