# Generated by Django 4.2.21 on 2025-06-03 07:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_travelplan_status_alter_travelplan_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="예: “서울역”, “제주공항” 등. 외부 API에서 받은 장소명이 있으면 저장",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("origin", "출발지"), ("destination", "목적지")],
                        help_text="origin 또는 destination 중 하나",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="외부 API(예: Geoapify)에서 받은 전체 주소 문자열",
                        max_length=255,
                    ),
                ),
                ("lat", models.FloatField(help_text="위도(latitude)")),
                ("lng", models.FloatField(help_text="경도(longitude)")),
                (
                    "place_id",
                    models.CharField(
                        blank=True,
                        help_text="Googleplaces API에서 제공하는 고유 장소 ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="planner.travelplan",
                    ),
                ),
            ],
        ),
    ]
